spring.application.name=API-GATEWAY
server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/user_audit_db
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Route for Provenance microservice
spring.cloud.gateway.server.webmvc.routes[0].id=provenance-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://PROVENANCE-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/provenance/**,/api/audit-packages/**,/api/dataset-snapshot/**

# Route for Study microservice
spring.cloud.gateway.server.webmvc.routes[1].id=study-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://STUDY-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/studies/**

# Route for Consent microservice
spring.cloud.gateway.server.webmvc.routes[2].id=consent-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://CONSENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/consents/**,/api/participants/**

# Route for Visit microservice
spring.cloud.gateway.server.webmvc.routes[3].id=consent-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://VISIT-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/sourcedata/**,/api/visits/**

# Disable Api gateway to register in eureka server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=true