spring.application.name=PROVENANCE-SERVICE
server.port=9191

EXTERNAL_STORAGE_PATH=C:/Users/2485063/IdeaProjects/microservice-mini-project

spring.datasource.url=jdbc:mysql://localhost:3306/provenance_db
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true